### ISSUE TITLE
No configure script

### ISSUE THREAD

**Issue by nealmcb** [KoreLogicSecurity/libklel#1]
`README.INSTALL` says:

```
To build and install the software associated with this library, run
  the following commands from within a bash shell:

    $ ./configure
```

But there is no `configure` script included in e.g. the `libklel-1.2.0.zip` release.

**Comment by KoreLogicSecurity** [comment]
The ZIP file produced by GitHub is not an official release. That's why it does not contain a configure script. You can download the official, digitally-signed 1.2.0 release tar ball from either of the following locations:

  - https://git.korelogic.com/libklel.git/
  - https://sourceforge.net/projects/libklel/files/libklel/1.2.0/
